//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainStation.Resources.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrainStation.Resources.Views.Home.index", typeof(index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy a ticket.
        /// </summary>
        public static string BuyTicket {
            get {
                return ResourceManager.GetString("BuyTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day after tomorrow.
        /// </summary>
        public static string DayAfterTomorrow {
            get {
                return ResourceManager.GetString("DayAfterTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure date.
        /// </summary>
        public static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure time.
        /// </summary>
        public static string DepartureTime {
            get {
                return ResourceManager.GetString("DepartureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email is required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an email address....
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending message!.
        /// </summary>
        public static string ErrorSendingMessage {
            get {
                return ResourceManager.GetString("ErrorSendingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyiv.
        /// </summary>
        public static string HotCity1 {
            get {
                return ResourceManager.GetString("HotCity1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lviv.
        /// </summary>
        public static string HotCity2 {
            get {
                return ResourceManager.GetString("HotCity2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przemyśl.
        /// </summary>
        public static string HotCity3 {
            get {
                return ResourceManager.GetString("HotCity3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dnipro-Main.
        /// </summary>
        public static string HotCity4 {
            get {
                return ResourceManager.GetString("HotCity4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odesa.
        /// </summary>
        public static string HotCity5 {
            get {
                return ResourceManager.GetString("HotCity5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy ticket.
        /// </summary>
        public static string MakeTicket {
            get {
                return ResourceManager.GetString("MakeTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middlename.
        /// </summary>
        public static string Middlename {
            get {
                return ResourceManager.GetString("Middlename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Me!.
        /// </summary>
        public static string Notify {
            get {
                return ResourceManager.GetString("Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have some questions?.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Train Station.
        /// </summary>
        public static string TrainStation {
            get {
                return ResourceManager.GetString("TrainStation", resourceCulture);
            }
        }
    }
}
